# Generated by Django 3.2.4 on 2021-07-02 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 2, 15, 24, 22, 899379)),
        ),
    ]
