# Generated by Django 2.2.14 on 2021-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], max_length=30)),
                ('info', models.CharField(max_length=100)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('phoneNumer', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
