# Generated by Django 3.2.4 on 2021-07-02 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210702_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
