# Generated by Django 3.2 on 2022-08-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgesVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 9, 18, 45, 43, 873436))),
                ('upload_file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
