# Generated by Django 3.2 on 2022-07-23 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agesverification',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 12, 6, 29, 74137)),
        ),
    ]
